#!/bin/bash

ProgRunAsName="${0}"
Arg1="${1}"
Arg2="${2}"
AllArgs="${@}"

ProgFileName="$( basename "${ProgRunAsName}" )"

echo "This program's name is: "${ProgFileName}""
echo Argument 1 is: "${Arg1}"
echo Argument 2 is: "${Arg2}"
echo All Arguments are: "${AllArgs}"

if [[ "${ProgFileName}" == "greetme" ]]
then

	Name="${Arg1}"

	while [[ "${Name}" == "" ]]
	do
		read -p "What is your name? " Name
	done

	echo "Hello ${Name}"
else
	echo "Get this scrript to run without errors first, then rename this script greetme to unlock something cool."
fi

exit 0
