#!/bin/bash

ifConfigVar=$(ifconfig en0 | grep "inet 10.2.225.2 netmask 0xffff0000 broadcast 10.2.255.255")
if [[ ${ifConfigVar} == true ]]
then 
	echo "$(date +%s)" > timeStuff/"$(date +%Y%m%d)"

fi
            
